version: '3.9'

networks:
  bookmytrip-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
  rabbitmq-data:
  elasticsearch-data:

services:

  mongodb:
    image: mongo:7.0
    container_name: bmt-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - bookmytrip-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: bmt-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bookmytrip-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: bmt-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - bookmytrip-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: bmt-elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - bookmytrip-network
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: unless-stopped