import { Router } from 'express';
import { z } from 'zod';

const router: Router = Router();

const itinerarySchema = z.object({
  from: z.string().min(2),
  destination: z.string().min(2),
  days: z.number().int().min(1).max(20),
  budget: z.number().positive(),
  interests: z.array(z.string()).default([]),
});

const supportSchema = z.object({
  message: z.string().min(3).max(1200),
  context: z.record(z.string(), z.unknown()).optional(),
});

router.post('/itinerary-suggestions', (req, res) => {
  const parsed = itinerarySchema.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ success: false, message: 'Validation failed', code: 'VALIDATION_ERROR' });
    return;
  }

  const { destination, days, budget, interests, from } = parsed.data;
  const perDay = Math.floor(budget / days);
  const suggestions = Array.from({ length: days }).map((_, index) => ({
    day: index + 1,
    headline: `Day ${index + 1} in ${destination}`,
    activities: [
      `Explore local highlights near ${destination}`,
      interests[0] ? `Focus on ${interests[0]} experiences` : 'Add one curated experience',
      `Target spend: around INR ${perDay}`,
    ],
  }));

  res.status(200).json({
    success: true,
    message: 'Itinerary generated',
    data: {
      from,
      destination,
      days,
      budget,
      suggestions,
      disclaimer: 'Generated by rule-based fallback planner. Plug provider key for LLM enhancement.',
    },
  });
});

router.post('/support', (req, res) => {
  const parsed = supportSchema.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ success: false, message: 'Validation failed', code: 'VALIDATION_ERROR' });
    return;
  }

  const msg = parsed.data.message.toLowerCase();
  const reply = msg.includes('refund')
    ? 'Refunds depend on fare rules and cancellation window. Open your booking and check the refund panel before submitting.'
    : msg.includes('payment')
      ? 'For payment failures, verify card details and retry once. If amount is debited, do not retry immediately; check payment status in booking history.'
      : 'I can help with itinerary, booking status, refunds, and offer eligibility. Share booking reference or route for a precise answer.';

  res.status(200).json({ success: true, message: 'Support response generated', data: { reply } });
});

export default router;
